<?php
/*
	OpenCart Shopping Cart

	Quick Edit created by AvanOsch for http://www.CrystalCopy.nl

	***********************************************************
	****      THIS FILE IS AUTOMATICALLY GENERATED!!!      ****
	****     USE ADMIN AREA TO CHANGE YOUR SETTINGS!!!     ****
	***********************************************************
	Released under the GNU General Public License
*/

  // Inline Edit
  define('QE_INLINE_NAME', 1);
  define('QE_INLINE_MODEL', 1);
  define('QE_INLINE_PRICE', 1);
  define('QE_INLINE_CATEGORY', 1);
  define('QE_INLINE_QUANTITY', 1);
  define('QE_INLINE_STATUS', 1);
  define('QE_INLINE_AUTOCLOSE', 1);
  define('QE_INLINE_AUTOSAVE', 1);
  define('QE_DEFAULT_SORT', 'p.price');
  define('QE_DEFAULT_ORDER', '');
  // Quick Edit
  define('QE_QUICK_MODEL', 1);
  define('QE_QUICK_MANUFACTURER', '');
  define('QE_QUICK_SKU', 1);
  define('QE_QUICK_UPC', 1);
  define('QE_QUICK_PRICE', '');
  define('QE_QUICK_TAX', '');
  define('QE_QUICK_QTY', '');
  define('QE_QUICK_SEO', 1);
  define('QE_QUICK_DATE', '');
  define('QE_QUICK_SIZE', 1);
  define('QE_QUICK_LENGTH', 1);
  define('QE_QUICK_WEIGHT', 1);
  define('QE_QUICK_WEIGHTCLASS', '');
  define('QE_QUICK_POINTS', '');
  define('QE_QUICK_REWARD', '');
  define('QE_QUICK_STATUS', '');
  define('QE_QUICK_SORT', '');
  define('QE_CATEGORY_HEIGHT', 250);
  define('QE_DIALOG_WIDTH', 480);
  define('QE_DIALOG_HEIGHT', 0);
  define('QE_QUICK_TIME', 800);
?>